""

load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "lecs",
    srcs = glob([ "src/**/*.hxx" ]),
    hdrs = glob([ "src/**/*.hxx" ]),
    includes = [ "src/" ],
    copts = select({
        "@rules_cc//cc/compiler:msvc-cl": ["/std:c++20"],
        "//conditions:default": ["-std=c++20"],
    }),
    include_prefix = "",
    strip_include_prefix = "src",
    linkstatic = True,
    visibility = ["//visibility:public"],
)
