load("@rules_cc//cc:defs.bzl", "cc_test")

cc_test(
    name = "units",
    srcs = [ "base_lecs_tests.hxx", "tests.cxx" ] + glob([ "units/**/*.cxx" ],),
    includes = [ "tests/" ],
    copts = select({
        "@rules_cc//cc/compiler:msvc-cl": ["/std:c++20"],
        "//conditions:default": ["-std=c++20"],
    }),
    deps = [ "@streamformat//:StreamFormat", "//:lecs" ],
    visibility = ["//visibility:public"],
)

cc_test(
    name = "perf",
    srcs = [ "base_lecs_tests.hxx", "tests.cxx" ] + glob([ "perf/**/*.cxx" ]),
    includes = [ "tests/" ],
    copts = select({
        "@rules_cc//cc/compiler:msvc-cl": ["/std:c++20"],
        "//conditions:default": ["-std=c++20"],
    }),
    deps = [ "@streamformat//:StreamFormat", "//:lecs" ],
    visibility = ["//visibility:public"],
)
