agents:
  queue: "agent-runners-linux-amd64"

steps:
  - label: ":bazel: Build and Test on gcc"
    commands:
      - CC=gcc bazelisk build //tests:units
      - CC=gcc bazelisk test //tests:units

  - label: ":bazel: Build and Test on Clang"
    commands:
      - CC=clang bazelisk build //tests:units
      - CC=clang bazelisk test //tests:units