agents:
  queue: "agent-runners-linux-amd64"

steps:
  - label: ":bazel: Build and Test on gcc"
    commands:
      - CC=gcc bazelisk build //:LittleECSTests
      - CC=gcc bazelisk test //:LittleECSTests

  - label: ":bazel: Build and Test on Clang"
    commands:
      - CC=clang bazelisk build //:LittleECSTests
      - CC=clang bazelisk test //:LittleECSTests